name: Deploy to neocities

on:
  push:
    branches:
      - main # run this job when I push to main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v6
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        dist_dir: "public/"
        neocities_supporter: true